chocolateBars = ['snickers', 'hundred grand', 'kitkat', 'skittles'];
var addElementToBeginningOfArray = (array, element) => [element, ...array];
var destructivelyAddElementToBeginningOfArray = (array, element) => array.unshift(element);
var addElementToEndOfArray = (array, element) => [...array, element];
var destructivelyAddElementToEndOfArray = (array, element) => array.push(element);
var destructivelyRemoveElementFromBeginningOfArray = (array) => array.shift();
var removeElementFromBeginningOfArray = (array) => array.slice(1);
var destructivelyRemoveElementFromBeginningOfArray = (array, element) => array.shift();
var destructivelyRemoveElementFromEndOfArray = (array, element) => array.pop();
var accessElementInArray = (array, index) => array[index];